# Generated by Django 4.0.3 on 2022-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.IntegerField()),
                ('is_pro', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('average_mmr', models.IntegerField()),
                ('players', models.ManyToManyField(to='pro_tracker.player')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
